DROP TABLE IF EXISTS TestProject.ROLES CASCADE ;
CREATE TABLE IF NOT EXISTS TestProject.ROLES (
   ID SERIAL PRIMARY KEY,
   UUID SMALLINT NOT NULL,
   VERSION SERIAL NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   DESCRIPTION VARCHAR(200),
   ACTIVE BOOLEAN NOT NULL,
   CREATED_BY VARCHAR(100) NOT NULL,
   CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   MODIFIED_BY VARCHAR(100),
   MODIFIED_AT TIMESTAMP
);


ALTER TABLE TestProject.ROLES ADD CONSTRAINT UK_ROLES_UUID UNIQUE(UUID);
ALTER TABLE TestProject.ROLES ADD CONSTRAINT UK_ROLES_NAME UNIQUE(NAME);


